In [1]:
import numpy as np
import pandas as pd

import tensorflow as tf
from tensorflow import keras
from keras import optimizers

import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn import preprocessing


In [2]:
mydata = pd.read_csv("/content/drive/MyDrive/dataset/Book2.csv")

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:3326: DtypeWarning: Columns (1,2,3) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)


In [3]:
df = mydata.head()

df.dtypes


0           float64
tcp          object
private      object
S0           object
0.1         float64
0.2         float64
0.3         float64
0.4         float64
0.5         float64
0.6         float64
0.7         float64
0.8         float64
0.9         float64
0.10        float64
0.11        float64
0.12        float64
0.13        float64
0.14        float64
0.15        float64
0.16        float64
0.17          int64
0.18          int64
123           int64
17            int64
1           float64
1.1         float64
0.19        float64
0.20        float64
0.14.1      float64
0.07        float64
0.21        float64
255           int64
17.1          int64
0.07.1      float64
0.07.2      float64
0.22        float64
0.23        float64
1.2         float64
1.3         float64
0.24        float64
0.25        float64
neptune.     object
dtype: object

In [4]:
mydata = mydata.dropna()

In [5]:
mydata.info

<bound method DataFrame.info of          0   tcp  private   S0     0.1     0.2  0.3  0.4  0.5  0.6  ...  17.1  \
0      0.0   tcp  private  REJ     0.0     0.0  0.0  0.0  0.0  0.0  ...     7   
1      0.0   tcp  private   S0     0.0     0.0  0.0  0.0  0.0  0.0  ...    13   
2      0.0  icmp    ecr_i   SF  1032.0     0.0  0.0  0.0  0.0  0.0  ...   255   
3      0.0   tcp     http   SF   219.0  8187.0  0.0  0.0  0.0  0.0  ...   255   
4      0.0   tcp     http   SF   202.0  1352.0  0.0  0.0  0.0  0.0  ...   255   
...    ...   ...      ...  ...     ...     ...  ...  ...  ...  ...  ...   ...   
99029  0.0   tcp      ssh   S0     0.0     0.0  0.0  0.0  0.0  0.0  ...    14   
99030  0.0  icmp    ecr_i   SF  1032.0     0.0  0.0  0.0  0.0  0.0  ...   255   
99031  0.0   tcp  private   S0     0.0     0.0  0.0  0.0  0.0  0.0  ...    15   
99032  0.0  icmp    ecr_i   SF  1032.0     0.0  0.0  0.0  0.0  0.0  ...   255   
99033  0.0  icmp    ecr_i   SF  1032.0     0.0  0.0  0.0  0.0  0.0  ...   255

In [6]:
mydata.columns=['duration'
,'protocol_type'
,'service'
,'flag'
,'src_bytes'
,'dst_bytes'
,'land'
,'wrong_fragment'
,'urgent'
,'hot'
,'num_failed_logins'
,'logged_in'
,'num_compromised'
,'root_shell'
,'su_attempted'
,'num_root'
,'num_file_creations'
,'num_shells'
,'num_access_files'
,'num_outbound_cmds'
,'is_host_login'
,'is_guest_login'
,'count'
,'srv_count'
,'serror_rate'
,'srv_serror_rate'
,'rerror_rate'
,'srv_rerror_rate'
,'same_srv_rate'
,'diff_srv_rate'
,'srv_diff_host_rate'
,'dst_host_count'
,'dst_host_srv_count'
,'dst_host_same_srv_rate'
,'dst_host_diff_srv_rate'
,'dst_host_same_src_port_rate'
,'dst_host_srv_diff_host_rate'
,'dst_host_serror_rate'
,'dst_host_srv_serror_rate'
,'dst_host_rerror_rate'
,'dst_host_srv_rerror_rate'
,'attack']

In [7]:
mydata.head()


duration protocol_type  service flag  src_bytes  dst_bytes  land  \
0       0.0           tcp  private  REJ        0.0        0.0   0.0   
1       0.0           tcp  private   S0        0.0        0.0   0.0   
2       0.0          icmp    ecr_i   SF     1032.0        0.0   0.0   
3       0.0           tcp     http   SF      219.0     8187.0   0.0   
4       0.0           tcp     http   SF      202.0     1352.0   0.0   

   wrong_fragment  urgent  hot  ...  dst_host_srv_count  \
0             0.0     0.0  0.0  ...                   7   
1             0.0     0.0  0.0  ...                  13   
2             0.0     0.0  0.0  ...                 255   
3             0.0     0.0  0.0  ...                 255   
4             0.0     0.0  0.0  ...                 255   

   dst_host_same_srv_rate  dst_host_diff_srv_rate  \
0                    0.03                    0.08   
1                    0.05                    0.07   
2                    1.00                    0.00   
3                    1.00                    0.00   
4                    1.00                    0.00   

   dst_host_same_src_port_rate  dst_host_srv_diff_host_rate  \
0                         0.00                         0.00   
1                         0.00                         0.00   
2                         1.00                         0.00   
3                         0.20                         0.05   
4                         0.03                         0.04   

   dst_host_serror_rate  dst_host_srv_serror_rate  dst_host_rerror_rate  \
0                   0.0                       0.0                   1.0   
1                   1.0                       1.0                   0.0   
2                   0.0                       0.0                   0.0   
3                   0.0                       0.0                   0.0   
4                   0.0                       0.0                   0.0   

   dst_host_srv_rerror_rate    attack  
0                       1.0  neptune.  
1                       0.0  neptune.  
2                       0.0    smurf.  
3                       0.0   normal.  
4                       0.0   normal.  

[5 rows x 42 columns]

In [65]:
mydata['attack_code'],label = pd.factorize(mydata.attack)
mydata['protocol_type_code'] = pd.factorize(mydata.protocol_type)[0]
mydata['service_code'] = pd.factorize(mydata.service)[0]
mydata['flag_code'] = pd.factorize(mydata.flag)[0]

In [67]:
label

Index(['neptune.', 'smurf.', 'normal.', 'back.', 'teardrop.', 'warezclient.',
       'portsweep.', 'satan.', 'rootkit.', 'nmap.', 'ipsweep.', 'pod.',
       'guess_passwd.', 'land.', 'warezmaster.', 'multihop.',
       'buffer_overflow.', 'imap.', 'loadmodule.'],
      dtype='object')

In [66]:
mydata.attack.value_counts()

smurf.              56315
neptune.            21461
normal.             19535
back.                 409
satan.                321
ipsweep.              258
portsweep.            208
warezclient.          201
teardrop.             197
pod.                   54
nmap.                  47
guess_passwd.           8
land.                   5
warezmaster.            4
buffer_overflow.        4
imap.                   3
rootkit.                2
multihop.               1
loadmodule.             1
Name: attack, dtype: int64

In [10]:
mydata.protocol_type.value_counts()

icmp    56888
tcp     37995
udp      4151
Name: protocol_type, dtype: int64

In [11]:
mydata.service.value_counts()

ecr_i      56440
private    22203
http       12765
smtp        2018
other       1509
           ...  
IRC           12
X11            2
tim_i          2
urh_i          2
tftp_u         1
Name: service, Length: 64, dtype: int64

In [12]:
mydata.flag.value_counts()

SF        75945
S0        17520
REJ        5223
RSTR        190
RSTO        108
SH           22
S1           13
S2            5
S3            3
RSTOS0        3
OTH           2
Name: flag, dtype: int64

In [13]:
mydata.tail()

duration protocol_type  service flag  src_bytes  dst_bytes  land  \
99029       0.0           tcp      ssh   S0        0.0        0.0   0.0   
99030       0.0          icmp    ecr_i   SF     1032.0        0.0   0.0   
99031       0.0           tcp  private   S0        0.0        0.0   0.0   
99032       0.0          icmp    ecr_i   SF     1032.0        0.0   0.0   
99033       0.0          icmp    ecr_i   SF     1032.0        0.0   0.0   

       wrong_fragment  urgent  hot  ...  dst_host_srv_diff_host_rate  \
99029             0.0     0.0  0.0  ...                          0.0   
99030             0.0     0.0  0.0  ...                          0.0   
99031             0.0     0.0  0.0  ...                          0.0   
99032             0.0     0.0  0.0  ...                          0.0   
99033             0.0     0.0  0.0  ...                          0.0   

       dst_host_serror_rate  dst_host_srv_serror_rate  dst_host_rerror_rate  \
99029                   1.0                       1.0                   0.0   
99030                   0.0                       0.0                   0.0   
99031                   1.0                       1.0                   0.0   
99032                   0.0                       0.0                   0.0   
99033                   0.0                       0.0                   0.0   

       dst_host_srv_rerror_rate    attack  attack_code  protocol_type_code  \
99029                       0.0  neptune.            0                   0   
99030                       0.0    smurf.            1                   1   
99031                       0.0  neptune.            0                   0   
99032                       0.0    smurf.            1                   1   
99033                       0.0    smurf.            1                   1   

       service_code  flag_code  
99029            28          1  
99030             1          2  
99031             0          1  
99032             1          2  
99033             1          2  

[5 rows x 46 columns]

In [14]:
x = mydata[['duration'
,'protocol_type_code'
,'service_code'
,'flag_code'
,'src_bytes'
,'dst_bytes'
,'land'
,'wrong_fragment'
,'urgent'
,'hot'
,'num_failed_logins'
,'logged_in'
,'num_compromised'
,'root_shell'
,'su_attempted'
,'num_root'
,'num_file_creations'
,'num_shells'
,'num_access_files'
,'num_outbound_cmds'
,'is_host_login'
,'is_guest_login'
,'count'
,'srv_count'
,'serror_rate'
,'srv_serror_rate'
,'rerror_rate'
,'srv_rerror_rate'
,'same_srv_rate'
,'diff_srv_rate'
,'srv_diff_host_rate'
,'dst_host_count'
,'dst_host_srv_count'
,'dst_host_same_srv_rate'
,'dst_host_diff_srv_rate'
,'dst_host_same_src_port_rate'
,'dst_host_srv_diff_host_rate'
,'dst_host_serror_rate'
,'dst_host_srv_serror_rate'
,'dst_host_rerror_rate'
,'dst_host_srv_rerror_rate']]

y = mydata['attack_code']

In [15]:
y.value_counts()

1     56315
0     21461
2     19535
3       409
7       321
10      258
6       208
5       201
4       197
11       54
9        47
12        8
13        5
14        4
16        4
17        3
8         2
15        1
18        1
Name: attack_code, dtype: int64

In [16]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=25)


In [31]:
model = keras.Sequential()
model.add(keras.layers.Dense(512, input_shape=(41,), activation='relu'))
model.add(keras.layers.Dense(256, activation='relu'))
model.add(keras.layers.Dense(128, activation='relu'))
model.add(keras.layers.Dense(19, activation='softmax'))

In [34]:
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [35]:
model.fit(x_train, y_train, epochs=3, batch_size=10)

Epoch 1/3
7923/7923 [==============================] - 42s 5ms/step - loss: 69.0900 - accuracy: 0.9822
Epoch 2/3
7923/7923 [==============================] - 42s 5ms/step - loss: 52.8723 - accuracy: 0.9882
Epoch 3/3
7923/7923 [==============================] - 42s 5ms/step - loss: 64.0282 - accuracy: 0.9892


In [36]:
score = model.evaluate(x_test,y_test,batch_size=10)

1981/1981 [==============================] - 5s 3ms/step - loss: 35.0236 - accuracy: 0.9900


In [ ]:
score

[0.0, 0.5649517774581909]

In [37]:
pred = model.predict(x_test[:10])

1/1 [==============================] - 0s 82ms/step


In [38]:
len(pred)

10

In [39]:
for i in range(len(pred)):
  print(pred[i])

[0.         0.         0.99999994 0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.        ]
[0.0000000e+00 9.9714398e-01 7.4722343e-21 1.5490814e-28 0.0000000e+00
 2.8560411e-03 2.7552733e-22 0.0000000e+00 0.0000000e+00 1.8858457e-17
 2.0724474e-15 4.8192267e-23 1.7656298e-33 0.0000000e+00 0.0000000e+00
 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00]
[0.0000000e+00 9.9999982e-01 3.8901544e-28 9.4619392e-35 0.0000000e+00
 6.0282389e-08 5.4764301e-32 0.0000000e+00 0.0000000e+00 1.5708506e-24
 5.5025085e-22 3.5852886e-32 0.0000000e+00 0.0000000e+00 0.0000000e+00
 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00]
[0.0000000e+00 9.9999982e-01 3.8901544e-28 9.4619392e-35 0.0000000e+00
 6.0282389e-08 5.4764301e-32 0.0000000e+00 0.0000000e+00 1.5708506e-24
 5.5025085e-22 3.5852886e-32 0.0000000e+00 0.0000000e+00 0.0000000e+00
 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+0

In [46]:
print(y_test[:10])

18561    2
57271    1
17229    1
51878    1
97230    1
25354    0
97098    1
91631    1
63335    1
62339    2
Name: attack_code, dtype: int64


In [49]:
for i in range(10):
	print(np.where(pred[i] == max(pred[i])))

(array([2]),)
(array([1]),)
(array([1]),)
(array([1]),)
(array([1]),)
(array([0]),)
(array([1]),)
(array([1]),)
(array([1]),)
(array([2]),)


In [70]:
for i in range(len(pred)):
  print(np.where(pred[i] == max(pred[i])),y_test[i:i+1],label[y_test[i:i+1]])

(array([2]),) 18561    2
Name: attack_code, dtype: int64 Index(['normal.'], dtype='object')
(array([1]),) 57271    1
Name: attack_code, dtype: int64 Index(['smurf.'], dtype='object')
(array([1]),) 17229    1
Name: attack_code, dtype: int64 Index(['smurf.'], dtype='object')
(array([1]),) 51878    1
Name: attack_code, dtype: int64 Index(['smurf.'], dtype='object')
(array([1]),) 97230    1
Name: attack_code, dtype: int64 Index(['smurf.'], dtype='object')
(array([0]),) 25354    0
Name: attack_code, dtype: int64 Index(['neptune.'], dtype='object')
(array([1]),) 97098    1
Name: attack_code, dtype: int64 Index(['smurf.'], dtype='object')
(array([1]),) 91631    1
Name: attack_code, dtype: int64 Index(['smurf.'], dtype='object')
(array([1]),) 63335    1
Name: attack_code, dtype: int64 Index(['smurf.'], dtype='object')
(array([2]),) 62339    2
Name: attack_code, dtype: int64 Index(['normal.'], dtype='object')
